steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/luminous-shadow-436101-k4/abhinav-100940786/assignment:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/luminous-shadow-436101-k4/abhinav-100940786/assignment:$COMMIT_SHA']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
